### ISSUE TITLE
awslogs-agent-setup.py requires python version 2.6 - 3.5

### ISSUE THREAD

**Issue by xibriz** [5orenso/aws-ami-creation#4]
Using `ami-template-node.sh` produces the following error:

```
+ python3 ./awslogs-agent-setup.py -n --region eu-west-1 -c /tmp/awslogs.conf
ERROR: This script only supports python version 2.6 - 3.5
```

**Comment by lucas-cavalcanti-ads** [comment]
Forbidden
You don't have permission to access this resource.
Apache/2.4.41 (Ubuntu) Server at ec2-18-230-23-42.sa-east-1.compute.amazonaws.com Port 80

Mas aparentemente não sei em que processo isso começou a acontecer.

Alguém consegue me dar um help?
